### ISSUE TITLE
Typo in ice_plot() regarding _get_quantiles()

### ISSUE THREAD

**Issue by savvastj** [AustinRochford/PyCEbox#18]
There is a typo in the `ice_plot()` function when calling the `_get_quantiles()` function.  In lines 124 and 137,  the `ice_plot()` calls `__get_quantiles()` (which is undefined) instead of `_get_quantiles()`, which results in an error if trying to use quantiles or center the ICE curves.

**Comment by sri-latha** [comment]
Came on here to report the same issue with __get_quantiles() with an extra underscore. Is d-ICE supported in this package? Is that in the pipeline?

**Comment by spoonertaylor** [comment]
Hello, I just installed pycebox and am facing this issue. Has this been resolved or is there any idea why I would still be facing this issue? Thanks.

**Comment by AustinRochford** [comment]
How did you install `PyCEbox`? Since this isn't actively maintained, I don't believe I released the version with the change to PyPI.  Perhaps you could try installing from Gitub and see if you get the fix?

**Comment by dmbaker** [comment]
One way to fix this is to monkey patch the pycebox.ice module as the original code calls this function instead of the coded _get_quantiles...

```
import pycebox.ice as icebox
def __get_quantiles(x):
    return np.greater.outer(x, x).sum(axis=1) / x.size
icebox.__get_quantiles = __get_quantiles
```

**Comment by csdalvi** [comment]
> How did you install `PyCEbox`? Since this isn't actively maintained, I don't believe I released the version with the change to PyPI. Perhaps you could try installing from Gitub and see if you get the fix?

I tried installing from github but it still shows the same issue

**Comment by farshidafshar** [comment]
> One way to fix this is to monkey patch the pycebox.ice module as the original code calls this function instead of the coded _get_quantiles...
> 
> ```
> import pycebox.ice as icebox
> def __get_quantiles(x):
>     return np.greater.outer(x, x).sum(axis=1) / x.size
> icebox.__get_quantiles = __get_quantiles
> ```

this worked for me , thank you "dmbaker"
